data = {
    "Harvard": "MA",
    "Stanford": "CA",
    "Yale": "CT",
    "Princeton": "NJ",
    "MIT": "MA",
    "Columbia": "NY",
    "University of Chicago": "IL",
    "California Institute of Technology": "CA",
    "University of Pennsylvania": "PA",
    "Duke": "NC",
    "Northwestern": "IL",
    "Johns Hopkins": "MD",
    "University of California, Berkeley": "CA",
    "University of Michigan": "MI",
    "University of California, Los Angeles": "CA",
    "University of Virginia": "VA",
    "Cornell": "NY",
    "University of Washington": "WA",
    "University of California, San Diego": "CA",
    "University of North Carolina at Chapel Hill": "NC",
    "University of Southern California": "CA",
    "Rice": "TX",
    "Vanderbilt": "TN",
    "Emory": "GA",
    "University of Wisconsin-Madison": "WI",
    "University of Texas at Austin": "TX",
    "University of Florida": "FL",
    "University of Illinois at Urbana-Champaign": "IL",
    "Washington University in St. Louis": "MO",
    "University of Notre Dame": "IN",
    "University of California, Irvine": "CA",
    "University of California, Santa Barbara": "CA",
    "University of Miami": "FL",
    "University of Pittsburgh": "PA",
    "University of Minnesota": "MN",
    "Ohio State University": "OH",
    "University of Maryland, College Park": "MD",
    "University of California, Davis": "CA",
    "University of Arizona": "AZ",
    "University of Colorado Boulder": "CO",
    "University of Massachusetts Amherst": "MA",
    "University of California, Riverside": "CA",
    "University of Georgia": "GA",
    "Penn State University": "PA",
    "University of Washington, Seattle": "WA",
    "University of Connecticut": "CT",
    "Michigan State University": "MI",
    "University of Southern Mississippi": "MS",
    "University of South Carolina": "SC",
    "Florida State University": "FL",
    "University of Oregon": "OR",
    "Louisiana State University": "LA",
    "Iowa State University": "IA",
    "North Carolina State University": "NC",
    "Clemson University": "SC",
    "University of Kansas": "KS",
    "University of Tennessee": "TN",
    "University of Rhode Island": "RI",
    "University of Hawaii at Manoa": "HI",
    "University of New Mexico": "NM",
    "University of Alabama": "AL",
    "University of Kentucky": "KY",
    "Brigham Young University": "UT",
    "Southern Methodist University": "TX",
    "University of Denver": "CO",
    "University of the Pacific": "CA",
    "Pepperdine University": "CA",
    "Loyola University Chicago": "IL",
    "Santa Clara University": "CA",
    "Wheaton College": "IL",
    "Oberlin College": "OH",
    "Smith College": "MA",
    "Wellesley College": "MA",
    "Vassar College": "NY",
    "Barnard College": "NY",
    "Middlebury College": "VT",
    "Pomona College": "CA",
    "Claremont McKenna College": "CA",
    "Colby College": "ME",
    "Hamilton College": "NY",
    "Grinnell College": "IA",
    "Swarthmore College": "PA",
    "Haverford College": "PA",
    "Bates College": "ME",
    "Davidson College": "NC",
    "Furman University": "SC",
    "Rhodes College": "TN",
    "Skidmore College": "NY",
    "Carleton College": "MN",
    "Kenyon College": "OH",
    "Gustavus Adolphus College": "MN",
    "Wabash College": "IN",
    "Trinity College": "CT",
    "Union College": "NY",
    "Washington and Lee University": "VA",
    "Bryn Mawr College": "PA",
    "Mount Holyoke College": "MA",
    "Hampden-Sydney College": "VA",
    "Whitman College": "WA",
    "Colorado College": "CO",
    "Occidental College": "CA",
    "Lafayette College": "PA",
    "Colgate University": "NY",
    "Pitzer College": "CA",
    "Bard College": "NY",
    "Sarah Lawrence College": "NY",
    "Bennington College": "VT",
    "New York University": "NY",
    "Boston University": "MA",
    "George Washington University": "DC",
    "American University": "DC",
    "University of San Francisco": "CA",
    "DePaul University": "IL",
    "Marquette University": "WI",
    "Saint Louis University": "MO",
    "Creighton University": "NE",
    "University of Scranton": "PA",
    "Fairfield University": "CT",
    "Iona College": "NY",
    "Canisius College": "NY",
    "St. John’s University": "NY",
    "Quinnipiac University": "CT",
    "Northeastern University": "MA",
    "George Mason University": "VA",
    "James Madison University": "VA",
    "Virginia Tech": "VA",
    "Old Dominion University": "VA",
    "Towson University": "MD",
    "University of Maryland, Baltimore County": "MD",
    "University of Massachusetts Lowell": "MA",
    "California State University, Los Angeles": "CA",
    "California State University, Long Beach": "CA",
    "California State University, Fullerton": "CA",
    "San Diego State University": "CA",
    "San Francisco State University": "CA",
    "University of California, Santa Cruz": "CA",
    "CUNY City College": "NY",
    "CUNY Hunter College": "NY",
    "CUNY Brooklyn College": "NY",
    "CUNY Baruch College": "NY",
    "University of Illinois at Chicago": "IL",
    "Southern Illinois University": "IL",
    "University of North Texas": "TX",
    "University of Houston": "TX",
    "Texas A&M University": "TX",
    "Texas Tech University": "TX",
    "University of Oklahoma": "OK",
    "University of Arkansas": "AR",
    "University of Nebraska-Lincoln": "NE",
    "University of South Florida": "FL",
    "Florida International University": "FL",
    "University of Central Florida": "FL",
    "University of Southern California": "CA",
    "California State University, Sacramento": "CA",
    "California State University, Chico": "CA",
    "California State University, San Bernardino": "CA",
    "San Jose State University": "CA",
    "Cal Poly San Luis Obispo": "CA",
    "Cal Poly Pomona": "CA",
    "University of Southern California": "CA",
    "New Jersey Institute of Technology": "NJ",
    "Stevens Institute of Technology": "NJ",
    "Pratt Institute": "NY",
    "Fashion Institute of Technology": "NY",
    "Rochester Institute of Technology": "NY",
    "Worcester Polytechnic Institute": "MA",
    "Kennesaw State University": "GA",
    "Georgia Southern University": "GA",
    "Valdosta State University": "GA",
    "Georgia State University": "GA",
    "West Virginia University": "WV",
    "Marshall University": "WV",
    "University of Wyoming": "WY",
    "University of Alaska Anchorage": "AK",
    "University of Alaska Fairbanks": "AK",
    "Montana State University": "MT",
    "University of Montana": "MT",
    "Idaho State University": "ID",
    "Boise State University": "ID",
    "University of Nevada, Reno": "NV",
    "University of Nevada, Las Vegas": "NV",
    "University of Oregon": "OR",
    "Portland State University": "OR",
    "Southern Utah University": "UT",
    "Utah State University": "UT",
    "Brigham Young University": "UT",
    "Weber State University": "UT",
    "Southern Utah University": "UT",
    "Florida Atlantic University": "FL",
    "University of West Florida": "FL",
    "California State University, Stanislaus": "CA",
    "California State University, Bakersfield": "CA",
    "California State University, Monterey Bay": "CA",
    "California State University, San Marcos": "CA",
    "Sonoma State University": "CA",
    "Sacramento State University": "CA",
    "University of San Diego": "CA",
    "Azusa Pacific University": "CA",
    "Biola University": "CA",
    "Cal Baptist University": "CA",
    "Concordia University Irvine": "CA",
    "Point Loma Nazarene University": "CA",
    "The Master’s University": "CA",
    "Woodbury University": "CA",
    "National University": "CA",
    "La Sierra University": "CA",
    "Loma Linda University": "CA",
    "Pepperdine University": "CA",
    "Fresno State University": "CA",
    "University of San Francisco": "CA",
    "San Diego Christian College": "CA",
    "Menlo College": "CA",
    "Notre Dame de Namur University": "CA",
    "Dominican University of California": "CA",
    "Holy Names University": "CA",
    "Mount Saint Mary’s University": "CA",
    "Saint Mary’s College of California": "CA",
    "Stanford University": "CA",
    "San Francisco State University": "CA",
    "California Institute of the Arts": "CA",
    "Art Center College of Design": "CA",
    "California College of the Arts": "CA",
    "Otis College of Art and Design": "CA",
    "Fresno Pacific University": "CA",
    "William Jessup University": "CA",
    "Biola University": "CA",
    "Life Pacific University": "CA",
    "Hope International University": "CA",
    "Whittier College": "CA",
    "La Sierra University": "CA",
    "Californa State University, Northridge": "CA",
    "California State University, Dominguez Hills": "CA",
    "California State University, Channel Islands": "CA",
    "Benedict College": "SC",
    "Hampton University": "VA",
    "Howard University": "DC",
    "Texas Southern University": "TX",
    "Florida A&M University": "FL",
    "North Carolina A&T State University": "NC",
    "Prairie View A&M University": "TX",
    "Virginia State University": "VA",
    "Tennessee State University": "TN",
    "Grambling State University": "LA",
    "Alcorn State University": "MS",
    "Jackson State University": "MS",
    "Clark Atlanta University": "GA",
    "Morehouse College": "GA",
    "Spelman College": "GA",
    "University of the District of Columbia": "DC",
    "California State University, Los Angeles": "CA",
    "University of Central Florida": "FL",
    "Valdosta State University": "GA",
    "West Georgia Technical College": "GA",
    "Georgia Gwinnett College": "GA",
    "Georgia Highlands College": "GA",
    "Georgia State University": "GA",
    "Georgia Southwestern State University": "GA",
    "Georgia College & State University": "GA",
    "Columbus State University": "GA",
    "Clayton State University": "GA",
    "Kennesaw State University": "GA",
    "Mercer University": "GA",
    "Emory University": "GA",
    "Agnes Scott College": "GA",
    "Oglethorpe University": "GA",
    "Piedmont University": "GA",
    "Brenau University": "GA",
    "South Georgia State College": "GA",
    "Southern Crescent Technical College": "GA",
    "Atlanta Technical College": "GA",
    "DeKalb Technical College": "GA",
    "Lanier Technical College": "GA",
    "North Georgia Technical College": "GA",
    "South Georgia College": "GA",
    "Georgia Perimeter College": "GA",
    "Chattahoochee Technical College": "GA",
    "Albany State University": "GA",
    "Fort Valley State University": "GA",
    "Savannah State University": "GA",
    "University of Georgia": "GA",
    "University of West Georgia": "GA",
    "University of North Georgia": "GA",
    "Valdosta State University": "GA",
    "Kennesaw State University": "GA",
    "Southern Polytechnic State University": "GA",
    "Georgia Gwinnett College": "GA",
    "Georgia Highlands College": "GA",
    "Georgia Southwestern State University": "GA",
    "Georgia College & State University": "GA",
    "Columbus State University": "GA",
    "Clayton State University": "GA",
    "Mercer University": "GA",
    "Emory University": "GA",
    "Agnes Scott College": "GA",
    "Oglethorpe University": "GA",
    "Piedmont University": "GA",
    "Brenau University": "GA",
    "Georgia State University": "GA",
}





